# Generated by Django 3.1.7 on 2021-03-12 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0002_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('state',
                 models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Archived'), (4, 'Deleted')], default=1)),
                ('account',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_reports',
                                   to='core.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reports',
                                            to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
