# Generated by Django 3.1.7 on 2021-03-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210315_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
