# Generated by Django 3.1.7 on 2021-03-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pivot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_group_count', models.PositiveSmallIntegerField(default=10)),
                ('start_group', models.PositiveSmallIntegerField(default=10)),
                ('dimension', models.ManyToManyField(related_name='pivot_for_dimension', to='template.Dimension')),
                ('metrics', models.ManyToManyField(related_name='pivot_for_metric', to='template.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('dimension', models.ManyToManyField(related_name='chart_for_dimension', to='template.Dimension')),
                ('metrics', models.ManyToManyField(related_name='chart_for_metric', to='template.Metric')),
                ('pivot', models.ManyToManyField(blank=True, null=True, related_name='chart_for_pivot', to='template.Pivot')),
            ],
        ),
    ]
