# Generated by Django 3.1.7 on 2021-03-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_auto_20210322_1350'),
        ('template', '0002_auto_20210319_1933'),
    ]

    operations = [
    ]
