# Generated by Django 3.1.7 on 2021-03-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('template', '0003_merge_20210322_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('charts', models.ManyToManyField(related_name='template_for_chart', to='template.Chart')),
            ],
        ),
    ]
