# Generated by Django 3.1.7 on 2021-03-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0006_template_ga_view_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='filter',
            new_name='filter_expression',
        ),
    ]
