# Generated by Django 3.1.7 on 2021-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0007_auto_20210325_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='filter_expression',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
