# Generated by Django 3.1.7 on 2021-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
