# Generated by Django 3.1.7 on 2021-03-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='acc_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
