# Generated by Django 3.1.7 on 2021-03-15 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0002_auto_20210315_1022'),
        ('core', '0003_auto_20210312_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
